/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SuccessionRouteImport } from './routes/succession'
import { Route as VillageRouteImport } from './routes/village'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as ExplorerCodeRouteImport } from './routes/explorer_.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessionRoute = SuccessionRouteImport.update({
  id: '/succession',
  path: '/succession',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageRoute = VillageRouteImport.update({
  id: '/village',
  path: '/village',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerCodeRoute = ExplorerCodeRouteImport.update({
  id: '/explorer_/$code',
  path: '/explorer/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/compare': typeof CompareRoute
  '/explorer': typeof ExplorerRoute
  '/glossary': typeof GlossaryRoute
  '/profile': typeof ProfileRoute
  '/studio': typeof StudioRoute
  '/succession': typeof SuccessionRoute
  '/village': typeof VillageRoute
  '/workshop': typeof WorkshopRoute
  '/explorer/$code': typeof ExplorerCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/compare': typeof CompareRoute
  '/explorer': typeof ExplorerRoute
  '/glossary': typeof GlossaryRoute
  '/profile': typeof ProfileRoute
  '/studio': typeof StudioRoute
  '/succession': typeof SuccessionRoute
  '/village': typeof VillageRoute
  '/workshop': typeof WorkshopRoute
  '/explorer/$code': typeof ExplorerCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/compare': typeof CompareRoute
  '/explorer': typeof ExplorerRoute
  '/glossary': typeof GlossaryRoute
  '/profile': typeof ProfileRoute
  '/studio': typeof StudioRoute
  '/succession': typeof SuccessionRoute
  '/village': typeof VillageRoute
  '/workshop': typeof WorkshopRoute
  '/explorer_/$code': typeof ExplorerCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/compare'
    | '/explorer'
    | '/glossary'
    | '/profile'
    | '/studio'
    | '/succession'
    | '/village'
    | '/workshop'
    | '/explorer/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/compare'
    | '/explorer'
    | '/glossary'
    | '/profile'
    | '/studio'
    | '/succession'
    | '/village'
    | '/workshop'
    | '/explorer/$code'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/compare'
    | '/explorer'
    | '/glossary'
    | '/profile'
    | '/studio'
    | '/succession'
    | '/village'
    | '/workshop'
    | '/explorer_/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  CompareRoute: typeof CompareRoute
  ExplorerRoute: typeof ExplorerRoute
  GlossaryRoute: typeof GlossaryRoute
  ProfileRoute: typeof ProfileRoute
  StudioRoute: typeof StudioRoute
  SuccessionRoute: typeof SuccessionRoute
  VillageRoute: typeof VillageRoute
  WorkshopRoute: typeof WorkshopRoute
  ExplorerCodeRoute: typeof ExplorerCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/succession': {
      id: '/succession'
      path: '/succession'
      fullPath: '/succession'
      preLoaderRoute: typeof SuccessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village': {
      id: '/village'
      path: '/village'
      fullPath: '/village'
      preLoaderRoute: typeof VillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer_/$code': {
      id: '/explorer_/$code'
      path: '/explorer/$code'
      fullPath: '/explorer/$code'
      preLoaderRoute: typeof ExplorerCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  CompareRoute: CompareRoute,
  ExplorerRoute: ExplorerRoute,
  GlossaryRoute: GlossaryRoute,
  ProfileRoute: ProfileRoute,
  StudioRoute: StudioRoute,
  SuccessionRoute: SuccessionRoute,
  VillageRoute: VillageRoute,
  WorkshopRoute: WorkshopRoute,
  ExplorerCodeRoute: ExplorerCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
